[2023-09-13T08:20:05.744+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:10:00+00:00 [queued]>
[2023-09-13T08:20:05.772+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:10:00+00:00 [queued]>
[2023-09-13T08:20:05.774+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-13T08:20:05.819+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-13 08:10:00+00:00
[2023-09-13T08:20:05.835+0000] {standard_task_runner.py:57} INFO - Started process 258 to run task
[2023-09-13T08:20:05.851+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-13T08:10:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpazr0875o']
[2023-09-13T08:20:05.863+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask exchange_data_task
[2023-09-13T08:20:05.947+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:10:00+00:00 [running]> on host cb4016c405b8
[2023-09-13T08:20:06.054+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T08:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-13T08:10:00+00:00'
[2023-09-13T08:20:06.420+0000] {logging_mixin.py:151} INFO - Connected
[2023-09-13T08:20:06.421+0000] {logging_mixin.py:151} INFO - ('2023-09-13 08:20:06','BTC','RUB',2486126.365854)
[2023-09-13T08:20:06.447+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-13T08:20:06.471+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230913T081000, start_date=20230913T082005, end_date=20230913T082006
[2023-09-13T08:20:06.542+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-13T08:20:06.583+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-29T14:35:20.238+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:20.251+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:20.407+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:20.411+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:20.473+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:10:00+00:00 [queued]>
[2023-10-29T14:35:20.575+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:10:00+00:00 [queued]>
[2023-10-29T14:35:20.578+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-29T14:35:21.175+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-13 08:10:00+00:00
[2023-10-29T14:35:21.230+0000] {standard_task_runner.py:57} INFO - Started process 273 to run task
[2023-10-29T14:35:21.248+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-13T08:10:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpqr1ve1po']
[2023-10-29T14:35:21.257+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask exchange_data_task
[2023-10-29T14:35:21.426+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:21.427+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:10:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:21.431+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:10:00+00:00 [running]> on host 452e7b951e9d
[2023-10-29T14:35:21.689+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T08:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-13T08:10:00+00:00'
[2023-10-29T14:35:22.207+0000] {logging_mixin.py:151} INFO - Connected
[2023-10-29T14:35:22.208+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 35, in exchange_data
    data = [(today, 'BTC', 'RUB', data['rates']['RUB'])]
KeyError: 'rates'
[2023-10-29T14:35:22.227+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230913T081000, start_date=20231029T143520, end_date=20231029T143522
[2023-10-29T14:35:22.273+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task exchange_data_task ('rates'; 273)
[2023-10-29T14:35:22.383+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-29T14:35:22.444+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
