[2023-09-13T08:30:05.506+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:20:00+00:00 [queued]>
[2023-09-13T08:30:05.517+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:20:00+00:00 [queued]>
[2023-09-13T08:30:05.518+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-13T08:30:05.545+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-13 08:20:00+00:00
[2023-09-13T08:30:05.552+0000] {standard_task_runner.py:57} INFO - Started process 404 to run task
[2023-09-13T08:30:05.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-13T08:20:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpjm026obb']
[2023-09-13T08:30:05.561+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask exchange_data_task
[2023-09-13T08:30:05.620+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:20:00+00:00 [running]> on host cb4016c405b8
[2023-09-13T08:30:05.724+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-13T08:20:00+00:00'
[2023-09-13T08:30:06.145+0000] {logging_mixin.py:151} INFO - Connected
[2023-09-13T08:30:06.147+0000] {logging_mixin.py:151} INFO - ('2023-09-13 08:30:06','BTC','RUB',2486126.365854)
[2023-09-13T08:30:06.167+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-13T08:30:06.229+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230913T082000, start_date=20230913T083005, end_date=20230913T083006
[2023-09-13T08:30:06.294+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-13T08:30:06.336+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-29T14:35:23.384+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:23.399+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:23.466+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:23.469+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:23.530+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:20:00+00:00 [queued]>
[2023-10-29T14:35:23.554+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:20:00+00:00 [queued]>
[2023-10-29T14:35:23.555+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-29T14:35:24.001+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-13 08:20:00+00:00
[2023-10-29T14:35:24.013+0000] {standard_task_runner.py:57} INFO - Started process 275 to run task
[2023-10-29T14:35:24.020+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-13T08:20:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpmpy3umt_']
[2023-10-29T14:35:24.027+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask exchange_data_task
[2023-10-29T14:35:24.103+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:24.103+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:20:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:24.106+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:20:00+00:00 [running]> on host 452e7b951e9d
[2023-10-29T14:35:24.236+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-13T08:20:00+00:00'
[2023-10-29T14:35:24.727+0000] {logging_mixin.py:151} INFO - Connected
[2023-10-29T14:35:24.728+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 35, in exchange_data
    data = [(today, 'BTC', 'RUB', data['rates']['RUB'])]
KeyError: 'rates'
[2023-10-29T14:35:24.745+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230913T082000, start_date=20231029T143523, end_date=20231029T143524
[2023-10-29T14:35:24.768+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task exchange_data_task ('rates'; 275)
[2023-10-29T14:35:24.802+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-29T14:35:24.831+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
