[2023-09-12T14:35:06.646+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-12T14:30:00+00:00 [queued]>
[2023-09-12T14:35:06.714+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-12T14:30:00+00:00 [queued]>
[2023-09-12T14:35:06.720+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-12T14:35:06.768+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-12 14:30:00+00:00
[2023-09-12T14:35:06.806+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2023-09-12T14:35:06.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-12T14:30:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpyj2pbiew']
[2023-09-12T14:35:06.880+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask exchange_data_task
[2023-09-12T14:35:07.195+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-12T14:30:00+00:00 [running]> on host fbfbca5b9527
[2023-09-12T14:35:07.605+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-12T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-12T14:30:00+00:00'
[2023-09-12T14:35:07.980+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 23, in exchange_data
    connection = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-09-12T14:35:07.999+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230912T143000, start_date=20230912T143506, end_date=20230912T143507
[2023-09-12T14:35:08.535+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task exchange_data_task (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 202)
[2023-09-12T14:35:08.580+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-12T14:35:08.649+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-12T22:10:23.417+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task permission to 509
[2023-09-12T22:10:23.430+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task'
[2023-09-12T22:10:23.812+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task permission to 509
[2023-09-12T22:10:23.813+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task'
[2023-09-12T22:10:23.868+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-12T14:30:00+00:00 [queued]>
[2023-09-12T22:10:23.889+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-12T14:30:00+00:00 [queued]>
[2023-09-12T22:10:23.891+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-12T22:10:23.924+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-12 14:30:00+00:00
[2023-09-12T22:10:23.943+0000] {standard_task_runner.py:57} INFO - Started process 171 to run task
[2023-09-12T22:10:23.943+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-12T14:30:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpa9mf4bid']
[2023-09-12T22:10:23.949+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask exchange_data_task
[2023-09-12T22:10:24.059+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task permission to 509
[2023-09-12T22:10:24.061+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-12T14:30:00+00:00/task_id=exchange_data_task'
[2023-09-12T22:10:24.078+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-12T14:30:00+00:00 [running]> on host 8df8606c974e
[2023-09-12T22:10:24.619+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-12T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-12T14:30:00+00:00'
[2023-09-12T22:10:25.023+0000] {logging_mixin.py:151} INFO - Connected
[2023-09-12T22:10:25.027+0000] {logging_mixin.py:151} INFO - ('2023-09-12 22:10:25','BTC','RUB',2488040.439024)
[2023-09-12T22:10:25.051+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-12T22:10:25.116+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230912T143000, start_date=20230912T221023, end_date=20230912T221025
[2023-09-12T22:10:25.590+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-12T22:10:25.660+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
