[2023-09-13T08:50:05.647+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:40:00+00:00 [queued]>
[2023-09-13T08:50:05.670+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:40:00+00:00 [queued]>
[2023-09-13T08:50:05.671+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-13T08:50:05.705+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-13 08:40:00+00:00
[2023-09-13T08:50:05.717+0000] {standard_task_runner.py:57} INFO - Started process 707 to run task
[2023-09-13T08:50:05.727+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-13T08:40:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpuu7vezzo']
[2023-09-13T08:50:05.735+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask exchange_data_task
[2023-09-13T08:50:05.849+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:40:00+00:00 [running]> on host cb4016c405b8
[2023-09-13T08:50:06.043+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-13T08:40:00+00:00'
[2023-09-13T08:50:06.789+0000] {logging_mixin.py:151} INFO - Connected
[2023-09-13T08:50:06.790+0000] {logging_mixin.py:151} INFO - ('2023-09-13 08:50:06','BTC','RUB',2486126.365854)
[2023-09-13T08:50:06.801+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-13T08:50:06.812+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230913T084000, start_date=20230913T085005, end_date=20230913T085006
[2023-09-13T08:50:06.864+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-13T08:50:06.884+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-29T14:35:12.315+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:12.345+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:15.347+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:15.363+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:15.562+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:40:00+00:00 [queued]>
[2023-10-29T14:35:15.598+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:40:00+00:00 [queued]>
[2023-10-29T14:35:15.605+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-29T14:35:15.719+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): exchange_data_task> on 2023-09-13 08:40:00+00:00
[2023-10-29T14:35:15.767+0000] {standard_task_runner.py:57} INFO - Started process 265 to run task
[2023-10-29T14:35:15.789+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_tasks', 'exchange_data_task', 'scheduled__2023-09-13T08:40:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpo7u316pw']
[2023-10-29T14:35:15.815+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask exchange_data_task
[2023-10-29T14:35:16.480+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task permission to 509
[2023-10-29T14:35:16.481+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simple_tasks/run_id=scheduled__2023-09-13T08:40:00+00:00/task_id=exchange_data_task'
[2023-10-29T14:35:16.485+0000] {task_command.py:415} INFO - Running <TaskInstance: simple_tasks.exchange_data_task scheduled__2023-09-13T08:40:00+00:00 [running]> on host 452e7b951e9d
[2023-10-29T14:35:18.392+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_tasks' AIRFLOW_CTX_TASK_ID='exchange_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-13T08:40:00+00:00'
[2023-10-29T14:35:19.218+0000] {logging_mixin.py:151} INFO - Connected
[2023-10-29T14:35:19.219+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 35, in exchange_data
    data = [(today, 'BTC', 'RUB', data['rates']['RUB'])]
KeyError: 'rates'
[2023-10-29T14:35:19.309+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=simple_tasks, task_id=exchange_data_task, execution_date=20230913T084000, start_date=20231029T143515, end_date=20231029T143519
[2023-10-29T14:35:19.363+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task exchange_data_task ('rates'; 265)
[2023-10-29T14:35:19.418+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-29T14:35:19.469+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
